name: Main CI/CD pipeline

on:
  workflow_dispatch:
    inputs:
      Release:
        description: Provide release version
        required: true
env:
  CI: false
jobs:
  deploy-dev:
    environment:
      name: dev
      url: https://my-github-actions-test.herokuapp.com/
      
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - name: Install node
        uses: actions/setup-node@v2
        with:
          node-version: ${{matrix.node-version}}
      - name: Checkout to the repo
        uses: actions/checkout@v2
      - name: Install dependencies
        uses: borales/actions-yarn@v2.3.0
        with:
          cmd: install
      - name: Run tests
        uses: borales/actions-yarn@v2.3.0
        with:
          cmd: test
      - name: Run build
        uses: borales/actions-yarn@v2.3.0
        with:
          cmd: build
      - name: Store my-artifact
        uses: actions/upload-artifact@v2
        with:
          name: my-artifact
          path: build/**/*
      - name: Deploy
        uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: my-github-actions-test #Must be unique in Heroku
          heroku_email: papamafii2@gmail.com

  deploy-stage:
    environment:
      name: stage
      url: https://my-stage-github-actions-test.herokuapp.com/
    needs: [deploy-dev]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - name: Checkout to the repo
        uses: actions/checkout@v2
      - name: Download my-artifact
        uses: actions/download-artifact@v2
        with:
          name: my-artifact
          path: dist
      - name: Deploy
        uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: my-stage-github-actions-test #Must be unique in Heroku
          heroku_email: papamafii2@gmail.com
          appdir: dist

