name: Main CI on PR

on:
  pull_request:
    branches: [master]

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - name: Install node
        uses: actions/setup-node@v2
        with:
          node-version: ${{matrix.node-version}}
      - name: Checkout to the repo
        uses: actions/checkout@v2
      - name: Install dependencies
        uses: borales/actions-yarn@v2.3.0
        with:
          cmd: install
      - name: Run tests
        uses: borales/actions-yarn@v2.3.0
        with:
          cmd: test
